src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom_film = null;

    #[ORM\Column]
    private ?int $duree = null;

    #[ORM\Column(length: 255)]
    private ?string $Categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $Realisateur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFilm(): ?string
    {
        return $this->nom_film;
    }

    public function setNomFilm(string $nom_film): self
    {
        $this->nom_film = $nom_film;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getRealisateur(): ?string
    {
        return $this->Realisateur;
    }

    public function setRealisateur(string $Realisateur): self
    {
        $this->Realisateur = $Realisateur;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_film')
            ->add('duree')
            ->add('Categorie')
            ->add('Description')
            ->add('image')
            ->add('Realisateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/film',name:'film')]
class FilmController extends AbstractController
{
    #[Route('/', name: 'app_film_index', methods: ['GET'])]
    public function index(FilmRepository $filmRepository): Response
    {
        return $this->render('film/index.html.twig', [
            'films' => $filmRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_film_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FilmRepository $filmRepository): Response
    {
        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filmRepository->save($film, true);

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/new.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_show', methods: ['GET'])]
    public function show(Film $film): Response
    {
        return $this->render('film/show.html.twig', [
            'film' => $film,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_film_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Film $film, FilmRepository $filmRepository): Response
    {
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filmRepository->save($film, true);

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/edit.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_delete', methods: ['POST'])]
    public function delete(Request $request, Film $film, FilmRepository $filmRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$film->getId(), $request->request->get('_token'))) {
            $filmRepository->remove($film, true);
        }

        return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('app_film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">Delete</button>
</form>

templates/film/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_film_index') }}">back to list</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film index{% endblock %}

{% block body %}
    <h1>Film index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_film</th>
                <th>Duree</th>
                <th>Categorie</th>
                <th>Description</th>
                <th>Image</th>
                <th>Realisateur</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td>{{ film.id }}</td>
                <td>{{ film.nomFilm }}</td>
                <td>{{ film.duree }}</td>
                <td>{{ film.Categorie }}</td>
                <td>{{ film.Description }}</td>
                <td>{{ film.image }}</td>
                <td>{{ film.Realisateur }}</td>
                <td>
                    <a href="{{ path('app_film_show', {'id': film.id}) }}">show</a>
                    <a href="{{ path('app_film_edit', {'id': film.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_film_new') }}">Create new</a>
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film{% endblock %}

{% block body %}
    <h1>Create new Film</h1>

    {{ include('film/_form.html.twig') }}

    <a href="{{ path('app_film_index') }}">back to list</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <h1>Film</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ film.id }}</td>
            </tr>
            <tr>
                <th>Nom_film</th>
                <td>{{ film.nomFilm }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ film.duree }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ film.Categorie }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ film.Description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ film.image }}</td>
            </tr>
            <tr>
                <th>Realisateur</th>
                <td>{{ film.Realisateur }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_film_index') }}">back to list</a>

    <a href="{{ path('app_film_edit', {'id': film.id}) }}">edit</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}